# tomcat configuration
server:
  port: 8082
  servlet :
    context-path:

spring.application.name: adminServer

# log level
logging.level:
  root: WARN
  org.springframework: DEBUG
  org.apache.coyote.http11.Http11InputBuffer: DEBUG
  sample.mybatis.mapper: DEBUG
  org.apache.ibatis: DEBUG